package io.github.lingqiqi5211.crashcatcher.ui.util

import io.github.lingqiqi5211.crashcatcher.data.daemon.CrashKind
import io.github.lingqiqi5211.crashcatcher.data.daemon.ExportRedaction
import io.github.lingqiqi5211.crashcatcher.data.daemon.RecordDetail
import io.github.lingqiqi5211.crashcatcher.domain.model.DeviceInfo
import java.util.Locale

/**
 * The text a record turns into when it leaves the app.
 *
 * Shaped after the tool being replaced, deliberately: its `[Key]: value` block is what
 * gets pasted into issue trackers today, so a maintainer reading one of these already
 * knows where to look, and a bug report that used to be readable does not become
 * unfamiliar just because it was produced by a different tool.
 *
 * What is *not* copied from it: the environment block is assembled here rather than by
 * the daemon. Every field in it describes the device this is running on, which is the
 * same device the crash happened on, so a round trip to ask a privileged process for
 * `Build.MODEL` would buy nothing.
 *
 * [redaction] hides the four fields that identify a device or a private app, replacing
 * each with [REDACTED] rather than dropping the line — a reader can then see that
 * something was withheld instead of wondering whether it was ever collected.
 */
internal fun buildExportText(
    detail: RecordDetail,
    payload: String,
    redaction: ExportRedaction,
    device: DeviceInfo,
): String {
    val record = detail.record
    val group = detail.group

    return buildString {
        appendLine(BANNER)
        appendLine("    Generated by CrashCatcher ${device.managerVersionName}")
        appendLine("    Project URL: $PROJECT_URL")
        appendLine(BANNER)
        appendField("Device Brand", device.brand, hidden = redaction.hideDeviceBrand)
        appendField("Device Model", device.model, hidden = redaction.hideDeviceModel)
        appendField("Display", device.buildDisplayId, hidden = redaction.hideBuildDisplayId)
        appendField("Android Version", device.androidRelease)
        appendField("Android API Level", device.androidApiLevel.toString())
        appendField("System Locale", Locale.getDefault().toString())
        appendField("CPU ABI", device.supportedAbis.firstOrNull().orEmpty())
        appendField("Process ID", record.pid.toString())
        appendField("User ID", group.userId.toString())
        appendField("Package Name", group.packageName, hidden = redaction.hidePackageName)
        // Only when it differs: on a single-process app this line repeats the one above.
        if (!group.isMainProcess) {
            appendField("Process Name", group.processName, hidden = redaction.hidePackageName)
        }
        appendField("Version Name", record.appVersionName.orEmpty())
        appendField("Version Code", record.appVersionCode?.toString().orEmpty())
        appendField("Error Type", group.kind.exportLabel)
        appendField("Self Handled", group.selfHandled.toString())
        appendField("Crash Time", formatTimestamp(record.happenedAtMs))
        appendField("Occurrence", group.occurrence.toString())
        appendLine("[Stack Trace]:")
        append(payload.ifBlank { NO_PAYLOAD })
    }
}

/**
 * One `[Key]: value` line.
 *
 * A field the device could not supply reads `unknown`, which is a different statement
 * from [REDACTED]: one means nothing was collected, the other means the person sharing
 * this chose not to include it.
 */
private fun StringBuilder.appendField(key: String, value: String, hidden: Boolean = false) {
    val resolved = when {
        hidden -> REDACTED
        value.isBlank() -> UNKNOWN
        else -> value
    }
    appendLine("[$key]: $resolved")
}

/** How a crash kind is named in an exported report. */
private val CrashKind.exportLabel: String
    get() = when (this) {
        CrashKind.JavaException -> "JVM"
        CrashKind.Anr -> "ANR"
        CrashKind.NativeCrash -> "Native"
        CrashKind.Wtf -> "WTF"
    }

private const val BANNER = "================================================================"

private const val PROJECT_URL = "https://github.com/lingqiqi5211/CrashCatcher"

private const val REDACTED = "***"

private const val UNKNOWN = "unknown"

private const val NO_PAYLOAD = "[payload unavailable]"
