[package]
name = "cch_auth"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cch_packages = { workspace = true }
cch_apk_sig = { workspace = true }
libc = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
